"""Tests for dashboard restart contract — serve must handle SIGTERM cleanly.

Bug: systemctl restart sends SIGTERM. Without a handler, serve_forever()
is killed abruptly and the socket can linger in a broken state, causing
ConnectionResetError on the next process's accepted connections.

Root cause: cmd_serve only caught KeyboardInterrupt (SIGINT from Ctrl+C),
not SIGTERM. Python's default SIGTERM handler terminates the process
without calling httpd.server_close() or httpd.shutdown().

Fix: Register SIGTERM handler that calls httpd.shutdown() for clean exit.
Also set allow_reuse_address on ThreadedHTTPServer to prevent TIME_WAIT
port conflicts on rapid restarts.
"""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

FREQ_ROOT = Path(__file__).parent.parent


class TestServeSigtermHandler(unittest.TestCase):
    """cmd_serve must register a SIGTERM handler for clean shutdown."""

    def test_cmd_serve_registers_sigterm(self):
        """cmd_serve source must contain signal.SIGTERM handler registration."""
        src = (FREQ_ROOT / "freq" / "modules" / "serve.py").read_text()
        self.assertIn("signal.signal(signal.SIGTERM", src)

    def test_sigterm_calls_shutdown(self):
        """SIGTERM handler must call httpd.shutdown() not sys.exit()."""
        src = (FREQ_ROOT / "freq" / "modules" / "serve.py").read_text()
        self.assertIn("httpd.shutdown()", src)

    def test_no_sys_exit_in_sigterm(self):
        """SIGTERM handler should not call sys.exit — use shutdown() instead."""
        src = (FREQ_ROOT / "freq" / "modules" / "serve.py").read_text()
        # Find the sigterm handler function
        import re
        handler_match = re.search(
            r'def _sigterm_handler.*?(?=\n    signal\.signal)',
            src, re.DOTALL
        )
        if handler_match:
            handler_body = handler_match.group()
            self.assertNotIn("sys.exit", handler_body)


class TestServerSocketReuse(unittest.TestCase):
    """ThreadedHTTPServer must set allow_reuse_address for restart safety."""

    def test_allow_reuse_address_set(self):
        """ThreadedHTTPServer must have allow_reuse_address = True."""
        src = (FREQ_ROOT / "freq" / "modules" / "serve.py").read_text()
        self.assertIn("allow_reuse_address = True", src)

    def test_server_close_in_finally(self):
        """server_close() must be in the finally block, not just except."""
        src = (FREQ_ROOT / "freq" / "modules" / "serve.py").read_text()
        # Find the serve_forever block
        import re
        serve_block = re.search(
            r'httpd\.serve_forever\(\).*?httpd\.server_close\(\)',
            src, re.DOTALL
        )
        self.assertIsNotNone(serve_block, "server_close() must follow serve_forever()")
        block = serve_block.group()
        self.assertIn("finally:", block, "server_close() must be in finally block")


class TestSystemdUnitContract(unittest.TestCase):
    """Systemd unit generated by init must support clean restart."""

    def test_init_unit_has_restart_always(self):
        """init-generated systemd unit must restart on any exit."""
        src = (FREQ_ROOT / "freq" / "modules" / "init_cmd.py").read_text()
        self.assertIn("Restart=always", src)

    def test_init_unit_has_reasonable_restart_sec(self):
        """RestartSec must be >= 5 seconds to avoid port conflicts."""
        src = (FREQ_ROOT / "freq" / "modules" / "init_cmd.py").read_text()
        import re
        match = re.search(r'RestartSec=(\d+)', src)
        self.assertIsNotNone(match)
        restart_sec = int(match.group(1))
        self.assertGreaterEqual(restart_sec, 5)


if __name__ == "__main__":
    unittest.main()
