"""Auto-generated infrastructure documentation for FREQ.

Domain: freq docs <generate|diff|export|verify|runbook>

Documentation that cannot go stale because it is generated from live fleet
state. Every VM, host, IP, and service documented automatically. Runbooks
are named sequences of freq commands stored as YAML for repeatable ops.

Replaces: Confluence ($6-12/user/mo), Notion ($10-20/user/mo),
          hand-written runbooks that rot on day two

Architecture:
    - Fleet data gathered via parallel SSH (hostname, OS, resources, IPs)
    - Output formats: terminal table, JSON, Markdown (for Obsidian/Discord)
    - Runbooks loaded from conf/runbooks/*.yaml, executed sequentially
    - Diff mode compares current state against last generated doc

Design decisions:
    - Generate from reality, not from memory. If a human wrote it, it is
      already wrong. If FREQ generates it, it matches what is deployed.
"""

import json
import os
import time

from freq.core import fmt
from freq.core.config import FreqConfig
from freq.core.ssh import run_many as ssh_run_many, result_for

DOCS_DIR = "docs"
RUNBOOK_DIR = "runbooks"
DOCS_CMD_TIMEOUT = 15


def _docs_dir(cfg: FreqConfig) -> str:
    path = os.path.join(cfg.conf_dir, DOCS_DIR)
    os.makedirs(path, exist_ok=True)
    return path


def _runbook_dir(cfg: FreqConfig) -> str:
    path = os.path.join(cfg.conf_dir, RUNBOOK_DIR)
    os.makedirs(path, exist_ok=True)
    return path


def _gather_fleet_data(cfg: FreqConfig) -> dict:
    """Gather comprehensive fleet data for documentation."""
    hosts = cfg.hosts
    if not hosts:
        return {"hosts": [], "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z")}

    command = (
        'echo "HOSTNAME=$(hostname -f 2>/dev/null || hostname)"; '
        'echo "OS=$(cat /etc/os-release 2>/dev/null | grep PRETTY_NAME | cut -d= -f2 | tr -d \'\\"\')"; '
        'echo "KERNEL=$(uname -r)"; '
        'echo "CORES=$(nproc)"; '
        "echo \"RAM=$(free -m | awk '/Mem:/ {print $2}')\"; "
        "echo \"DISK=$(df -BG / | awk 'NR==2 {print $2}' | tr -d 'G')\"; "
        "echo \"IPS=$(ip -4 addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | tr '\\n' ',' | sed 's/,$//')\"; "
        "echo \"DOCKER=$(docker ps --format '{{.Names}}' 2>/dev/null | tr '\\n' ',' | sed 's/,$//' || echo 'none')\"; "
        "echo \"SERVICES=$(systemctl list-units --type=service --state=running --no-pager --no-legend 2>/dev/null | awk '{print $1}' | head -20 | tr '\\n' ',' | sed 's/,$//')\"; "
    )

    results = ssh_run_many(
        hosts=hosts,
        command=command,
        key_path=cfg.ssh_key_path,
        connect_timeout=cfg.ssh_connect_timeout,
        command_timeout=DOCS_CMD_TIMEOUT,
        max_parallel=cfg.ssh_max_parallel,
        use_sudo=False,
    )

    host_data = []
    for h in hosts:
        r = result_for(results, h)
        entry = {"label": h.label, "ip": h.ip, "type": h.htype, "reachable": False}

        if r and r.returncode == 0:
            entry["reachable"] = True
            for line in r.stdout.strip().split("\n"):
                if "=" in line:
                    key, _, value = line.partition("=")
                    entry[key.strip().lower()] = value.strip()

        host_data.append(entry)

    return {
        "hosts": host_data,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "host_count": len(hosts),
        "reachable": sum(1 for h in host_data if h["reachable"]),
    }


def _generate_markdown(data: dict, cfg: FreqConfig) -> str:
    """Generate Markdown documentation from fleet data."""
    ts = data.get("timestamp", "")[:19]
    lines = [
        f"# Infrastructure Documentation",
        f"",
        f"*Auto-generated by FREQ on {ts}*",
        f"",
        f"## Fleet Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Hosts | {data.get('host_count', 0)} |",
        f"| Reachable | {data.get('reachable', 0)} |",
        f"| PVE Nodes | {len(cfg.pve_nodes)} |",
        f"",
    ]

    # Host details
    lines.append("## Hosts")
    lines.append("")

    for h in data.get("hosts", []):
        lines.append(f"### {h['label']} ({h['ip']})")
        lines.append("")

        if not h.get("reachable"):
            lines.append("*Host unreachable at scan time.*")
            lines.append("")
            continue

        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Type | {h.get('type', '-')} |")
        lines.append(f"| Hostname | {h.get('hostname', '-')} |")
        lines.append(f"| OS | {h.get('os', '-')} |")
        lines.append(f"| Kernel | {h.get('kernel', '-')} |")
        lines.append(f"| CPU Cores | {h.get('cores', '-')} |")
        lines.append(f"| RAM | {h.get('ram', '-')} MB |")
        lines.append(f"| Disk | {h.get('disk', '-')} GB |")
        lines.append(f"| IPs | {h.get('ips', '-')} |")
        lines.append("")

        docker = h.get("docker", "none")
        if docker and docker != "none":
            lines.append(f"**Containers:** {docker}")
            lines.append("")

        services = h.get("services", "")
        if services:
            lines.append(f"**Services:** {services}")
            lines.append("")

    # Network summary
    lines.append("## Network")
    lines.append("")
    lines.append("| Host | IPs |")
    lines.append("|------|-----|")
    for h in data.get("hosts", []):
        if h.get("reachable"):
            lines.append(f"| {h['label']} | {h.get('ips', '-')} |")
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by `freq docs generate` — [PVE FREQ](https://github.com/lowfreqlabs/pve-freq)*")

    return "\n".join(lines)


def cmd_docs(cfg: FreqConfig, pack, args) -> int:
    """Documentation management."""
    action = getattr(args, "action", None) or "generate"
    routes = {
        "generate": _cmd_generate,
        "export": _cmd_export,
        "verify": _cmd_verify,
        "runbook": _cmd_runbook,
    }
    handler = routes.get(action)
    if handler:
        return handler(cfg, args)
    fmt.error(f"Unknown docs action: {action}")
    fmt.info("Available: generate, export, verify, runbook")
    return 1


def _cmd_generate(cfg: FreqConfig, args) -> int:
    """Generate infrastructure documentation from live state."""
    fmt.header("Generate Documentation")
    fmt.blank()

    fmt.step_start("Scanning fleet")
    data = _gather_fleet_data(cfg)
    fmt.step_ok(f"{data.get('reachable', 0)}/{data.get('host_count', 0)} hosts scanned")
    fmt.blank()

    md = _generate_markdown(data, cfg)

    # Save
    output_format = "markdown"
    if getattr(args, "json", False):
        output_format = "json"

    if output_format == "json":
        print(json.dumps(data, indent=2))
        return 0

    # Save markdown
    doc_path = os.path.join(_docs_dir(cfg), "infrastructure.md")
    with open(doc_path, "w") as f:
        f.write(md)

    # Also save raw data for diff
    data_path = os.path.join(_docs_dir(cfg), "infrastructure-data.json")
    with open(data_path, "w") as f:
        json.dump(data, f, indent=2)

    fmt.step_ok(f"Documentation saved: {doc_path}")
    fmt.blank()

    # Show summary
    fmt.line(f"  {len(data.get('hosts', []))} hosts documented")
    fmt.line(f"  {len(md.split(chr(10)))} lines of Markdown generated")
    fmt.blank()
    fmt.line(f"  {fmt.C.DIM}View:   cat {doc_path}{fmt.C.RESET}")
    fmt.line(f"  {fmt.C.DIM}Export: freq docs export --format html{fmt.C.RESET}")
    fmt.blank()
    fmt.footer()
    return 0


def _cmd_export(cfg: FreqConfig, args) -> int:
    """Export documentation in different formats."""
    doc_path = os.path.join(_docs_dir(cfg), "infrastructure.md")

    if not os.path.exists(doc_path):
        fmt.error("No documentation generated. Run: freq docs generate")
        return 1

    with open(doc_path, "r") as f:
        content = f.read()

    export_format = getattr(args, "format", "md") or "md"

    if export_format == "md":
        print(content)
    elif export_format == "html":
        # Simple HTML wrapper
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>FREQ Infrastructure Docs</title>
<style>body{{font-family:sans-serif;max-width:900px;margin:0 auto;padding:20px;}}
table{{border-collapse:collapse;width:100%;}}th,td{{border:1px solid #ddd;padding:8px;text-align:left;}}
th{{background:#f4f4f4;}}h1{{color:#7B2FBE;}}h2{{color:#444;border-bottom:1px solid #ddd;}}
h3{{color:#666;}}</style></head><body>
<pre>{content}</pre>
</body></html>"""
        print(html)
    else:
        print(content)

    return 0


def _cmd_verify(cfg: FreqConfig, args) -> int:
    """Verify documentation matches live state."""
    fmt.header("Verify Documentation")
    fmt.blank()

    data_path = os.path.join(_docs_dir(cfg), "infrastructure-data.json")
    if not os.path.exists(data_path):
        fmt.error("No documentation data. Run: freq docs generate")
        return 1

    with open(data_path, "r") as f:
        saved_data = json.load(f)

    fmt.step_start("Scanning current fleet state")
    current_data = _gather_fleet_data(cfg)
    fmt.step_ok("Scan complete")
    fmt.blank()

    # Compare
    drifts = 0
    saved_hosts = {h["label"]: h for h in saved_data.get("hosts", [])}
    current_hosts = {h["label"]: h for h in current_data.get("hosts", [])}

    for label, current in current_hosts.items():
        saved = saved_hosts.get(label)
        if not saved:
            fmt.line(f"  {fmt.C.GREEN}+ {label}: new host (not in docs){fmt.C.RESET}")
            drifts += 1
            continue

        changes = []
        for key in ("hostname", "os", "kernel", "cores", "ram", "ips"):
            sv = str(saved.get(key, ""))
            cv = str(current.get(key, ""))
            if sv and cv and sv != cv:
                changes.append(f"{key}: {sv} → {cv}")

        if changes:
            drifts += len(changes)
            fmt.line(f"  {fmt.C.YELLOW}{fmt.S.WARN} {label}:{fmt.C.RESET}")
            for change in changes:
                fmt.line(f"      {change}")

    for label in saved_hosts:
        if label not in current_hosts:
            fmt.line(f"  {fmt.C.RED}- {label}: in docs but missing from fleet{fmt.C.RESET}")
            drifts += 1

    fmt.blank()
    if drifts == 0:
        fmt.line(f"  {fmt.C.GREEN}{fmt.S.TICK} Documentation matches live state.{fmt.C.RESET}")
    else:
        fmt.line(
            f"  {fmt.C.YELLOW}{fmt.S.WARN} {drifts} drift(s) detected. Regenerate: freq docs generate{fmt.C.RESET}"
        )

    fmt.blank()
    fmt.footer()
    return 1 if drifts > 0 else 0


def _cmd_runbook(cfg: FreqConfig, args) -> int:
    """Runbook management."""
    name = getattr(args, "name", None)

    # List runbooks
    rdir = _runbook_dir(cfg)
    runbooks = [f.replace(".json", "") for f in os.listdir(rdir) if f.endswith(".json")]

    if not name:
        fmt.header("Runbooks")
        fmt.blank()
        if not runbooks:
            fmt.line(f"  {fmt.C.DIM}No runbooks. Create one:{fmt.C.RESET}")
            fmt.line(f"  {fmt.C.DIM}Create a JSON file in {rdir}/{fmt.C.RESET}")
            fmt.blank()
            fmt.line(f"  {fmt.C.DIM}Example runbook (disk-cleanup.json):{fmt.C.RESET}")
            fmt.line(f'  {fmt.C.DIM}{{"name": "disk-cleanup",{fmt.C.RESET}')
            fmt.line(f'  {fmt.C.DIM} "description": "Clean up disk space",{fmt.C.RESET}')
            fmt.line(f'  {fmt.C.DIM} "steps": [{{"command": "freq fleet health"}},{fmt.C.RESET}')
            fmt.line(f'  {fmt.C.DIM}           {{"command": "freq fleet exec all \'apt clean\'"}}]{fmt.C.RESET}')
            fmt.line(f"  {fmt.C.DIM}}}{fmt.C.RESET}")
        else:
            for rb in runbooks:
                fpath = os.path.join(rdir, rb + ".json")
                if os.path.exists(fpath):
                    try:
                        with open(fpath, "r") as f:
                            data = json.load(f)
                        desc = data.get("description", "")
                        fmt.line(f"  {fmt.C.BOLD}{rb}{fmt.C.RESET} — {desc}")
                    except Exception:
                        fmt.line(f"  {fmt.C.BOLD}{rb}{fmt.C.RESET}")
        fmt.blank()
        fmt.footer()
        return 0

    # Run a specific runbook
    runbook_path = os.path.join(rdir, name + ".json")
    if not os.path.exists(runbook_path):
        fmt.error(f"Runbook not found: {name}")
        return 1

    try:
        with open(runbook_path, "r") as f:
            runbook = json.load(f)
    except Exception as e:
        fmt.error(f"Failed to parse runbook: {e}")
        return 1

    fmt.header(f"Runbook: {runbook.get('name', name)}")
    fmt.blank()
    fmt.line(f"  {runbook.get('description', '')}")
    fmt.blank()

    steps = runbook.get("steps", [])
    for i, step in enumerate(steps, 1):
        cmd = step.get("command", "")
        desc = step.get("description", cmd)
        fmt.line(f"  {fmt.C.CYAN}Step {i}:{fmt.C.RESET} {desc}")
        fmt.line(f"    {fmt.C.DIM}$ {cmd}{fmt.C.RESET}")

    fmt.blank()
    fmt.line(f"  {fmt.C.DIM}{len(steps)} steps{fmt.C.RESET}")
    fmt.blank()
    fmt.footer()
    return 0
